/*
 * Example programs for the MIPS profile: content for the Examples menu, kept
 * out of the structural arch profile (arch/mips.js). Each entry is
 * { name, mode, code }; app.js loads them via `profile.examples`.
 *
 * Branch targets are absolute addresses: each line assembles at its real address
 * so it round-trips with the disassembler, but labels can't resolve across lines.
 * Keystone auto-fills every branch delay slot with a nop, so a branch LINE is 8
 * bytes. The addresses below assume the profile's default codeBase (0x10000) and
 * were run-verified in Unicorn (see tests/test_examples_node.mjs).
 */
export default [
    {
        name: "Sum loop (delay slots)",
        mode: "32",
        code: [
            "; Sum 1..10 into $t0, then store the result in the data region.",
            "; Branch lines are 8 bytes: Keystone fills the delay slot with a nop.",
            "ori $t0, $zero, 0",
            "ori $t1, $zero, 10",
            "addu $t0, $t0, $t1",
            "addiu $t1, $t1, -1",
            "bne $t1, $zero, 0x10008",
            "lui $t2, 2",
            "sw $t0, 0($t2)",
        ].join("\n"),
    },
    {
        name: "String upper-case (loop)",
        mode: "32",
        code: [
            '; Write "hello" into the data region, then upper-case it in a loop.',
            '; The word constant is big-endian, so "hell" lands in byte order.',
            "li $t0, 0x20000",
            "li $t1, 0x68656c6c",
            "sw $t1, 0($t0)",
            "li $t1, 0x6f",
            "sb $t1, 4($t0)",
            "li $t2, 5",
            "lbu $t3, 0($t0)",
            "addiu $t3, $t3, -32",
            "sb $t3, 0($t0)",
            "addiu $t0, $t0, 1",
            "addiu $t2, $t2, -1",
            "bne $t2, $zero, 0x1001c",
        ].join("\n"),
    },
    {
        name: "Function call & stack",
        mode: "32",
        code: [
            "; Sum of squares 1..5 via a subroutine: $s0 = 55, stored at 0x20000.",
            "; The callee keeps a stack frame (save/restore $ra and $a0), so",
            "; step-over/step-out have a real call to track. Entry jumps over it.",
            "b 0x1002c",
            "; SQUARE: $v0 = $a0 * $a0",
            "addiu $sp, $sp, -8",
            "sw $ra, 4($sp)",
            "sw $a0, 0($sp)",
            "mul $v0, $a0, $a0",
            "lw $a0, 0($sp)",
            "lw $ra, 4($sp)",
            "addiu $sp, $sp, 8",
            "jr $ra",
            "; MAIN: loop $s1 = 1..5, calling SQUARE each time",
            "ori $s0, $zero, 0",
            "ori $s1, $zero, 1",
            "ori $t0, $zero, 6",
            "addu $a0, $s1, $zero",
            "jal 0x10008",
            "addu $s0, $s0, $v0",
            "addiu $s1, $s1, 1",
            "bne $s1, $t0, 0x10038",
            "lui $t2, 2",
            "sw $s0, 0($t2)",
        ].join("\n"),
    },
    {
        name: "String upper-case (loop)",
        mode: "32le",
        code: [
            '; Write "hello" into the data region, then upper-case it in a loop.',
            '; The word constant is little-endian, so "hell" lands in byte order.',
            "li $t0, 0x20000",
            "li $t1, 0x6c6c6568",
            "sw $t1, 0($t0)",
            "li $t1, 0x6f",
            "sb $t1, 4($t0)",
            "li $t2, 5",
            "lbu $t3, 0($t0)",
            "addiu $t3, $t3, -32",
            "sb $t3, 0($t0)",
            "addiu $t0, $t0, 1",
            "addiu $t2, $t2, -1",
            "bne $t2, $zero, 0x1001c",
        ].join("\n"),
    },
    {
        name: "64-bit byte packing",
        mode: "64",
        code: [
            "; Pack bytes 0x01..0x08 into one register with 64-bit shifts",
            "; ($8 = 0x0102030405060708), store it with sd, load it back.",
            "; Registers are numeric in 64-bit modes: $8-$12 show as R8-R12.",
            "ori $8, $0, 0",
            "ori $9, $0, 1",
            "ori $10, $0, 9",
            "dsll $8, $8, 8",
            "daddu $8, $8, $9",
            "daddiu $9, $9, 1",
            "bne $9, $10, 0x1000c",
            "lui $11, 2",
            "sd $8, 0($11)",
            "ld $12, 0($11)",
        ].join("\n"),
    },
    {
        name: "64-bit byte packing",
        mode: "64le",
        code: [
            "; Pack bytes 0x01..0x08 into one register with 64-bit shifts",
            "; ($8 = 0x0102030405060708), store it with sd, load it back.",
            "; Registers are numeric in 64-bit modes: $8-$12 show as R8-R12.",
            "ori $8, $0, 0",
            "ori $9, $0, 1",
            "ori $10, $0, 9",
            "dsll $8, $8, 8",
            "daddu $8, $8, $9",
            "daddiu $9, $9, 1",
            "bne $9, $10, 0x1000c",
            "lui $11, 2",
            "sd $8, 0($11)",
            "ld $12, 0($11)",
        ].join("\n"),
    },
];
